### ISSUE TITLE
Change to Primary Care

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/snhc-web#12]
The Saturday Clinic should always be referred to as an episodic care clinic and never as a basic care or primary care clinic.

**Comment by justinrporter** [comment]
@ecd25 I would encourage you to make these sorts of changes yourself. Me doing it will just result in a sort of telephone tag of verbiage...

**Comment by justinrporter** [comment]
Fixable by anyone, does not demand programmer attention.
