### ISSUE TITLE
social work sign up

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/snhc-web#15]
sign up google doc from old website should go on social work tab

**Comment by justinrporter** [comment]
@ecd25 There wasn't a google doc signup on the old site. No reference whatsoever to social work students, in fact. Do you mean the one on sharepoint? If you do, we need to be aware that it's currently hidden from the public internet and putting it under social work will open it up, which is probably not what we want...

also @lizmaidl I'm ready to integrate your changes you made yesterday, this one one of them... do we still want to do that in light of above?

Will resolve #17

**Comment by lizmaidl** [comment]
You raise a good point. Maybe we need to reevaluate our social work sign ups... I don't want the entire world to be able to see that doc...

Elizabeth Maidl
Washington University School of Medicine in St. Louis
MD Candidate | Class of 2018
maidle@wusm.wustl.edu
(507) 272-1615

On Mar 6, 2015, at 12:43, Justin Porter notifications@github.com wrote:

@ecd25 There wasn't a google doc signup on the old site. No reference whatsoever to social work students, in fact. Do you mean the one on sharepoint? If you do, we need to be aware that it's currently
 hidden from the public internet and putting it under social work will open it up, which is probably not what we want...
also @lizmaidl I'm ready to integrate your changes you made yesterday, this one one of them... do we still want to do that in light of above?
�
Reply to this email directly or 
view it on GitHub.

 

The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended
 recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone
 or return mail.

**Comment by justinrporter** [comment]
From a hardcore security perspective, the entire world can already. It's
security by obscurity... If nobody types the URL just so, then nobody can
find it.

I'm working on a better solution to include the social work/OT students.
Stay tuned.

I'll revert your addition of that link, then merge your changes to master
and make them live.
