### ISSUE TITLE
add reminder to website

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/snhc-web#19]
Justin, can we add a reminder on the homepage? below the banner, above the 'patients, physicians, students' circles
Don't upload yet, I need to get the website and timing details from our contact; i will update this issue.
Thanks!!

Siteman Cancer Center Health Fair: free pap smears, HPV testing, and other services, with same-day results!
April 25

**Comment by radhikajain** [comment]
https://drive.google.com/file/d/0Bz1QXY4bzZkkaW9aY0JSd0Q0MlU/view?usp=sharing

This might work! Text for the site:

Join the Siteman Cancer Center for free pap smears, breast cancer screenings, and other general health screenings (including blood glucose, cholesterol, and HIV) on Saturday, April 25, from 8 am to 1:30 pm. See this flyer [hyperlink] for more information on services, timing, and location.

**Comment by justinrporter** [comment]
![screen shot 2015-04-06 at 4 49 04 pm](https://cloud.githubusercontent.com/assets/3531723/7013188/e1c7addc-dc7c-11e4-997c-e0a4770582bd.png)

Implemented by d881b9d. Changes go live at midnight.

**Comment by radhikajain** [comment]
beautiful thank you @justinrporter!!
