### ISSUE TITLE
put facebook on the webpage

### ISSUE THREAD

**Issue by lizmaidl** [SaturdayNeighborhoodHealthClinic/snhc-web#22]
@justinrporter 
@justinrporter 
@justinrporter 
@justinrporter 
@justinrporter 
@justinrporter 
@justinrporter 
@justinrporter

**Comment by lizmaidl** [comment]
@justinrporter

**Comment by lizmaidl** [comment]
@justinrporter

**Comment by lizmaidl** [comment]
@justinrporter

**Comment by justinrporter** [comment]
So... is there, like, a button I need to add, or a link, or what? What did you have in mind?

**Comment by lizmaidl** [comment]
maybe a button? something like this?
https://developers.facebook.com/docs/plugins/like-buttonhttps://developers.facebook.com/docs/plugins/like-button

1. Include the JavaScript SDK on your page once, ideally right after the opening <body> tag.

<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

2. Place the code for your plugin wherever you want the plugin to appear on your page.

<div class="fb-like" data-href="https://www.facebook.com/wusmsnhc?ref=hl" data-layout="box_count" data-action="like" data-show-faces="true" data-share="true"></div>

Elizabeth Maidl
Washington University School of Medicine in St. Louis
MD Candidate | Class of 2018
maidle@wusm.wustl.edu
(507) 272-1615

**Comment by lizmaidl** [comment]
oooh, or i might like this better: 
https://developers.facebook.com/docs/plugins/page-plugin/

<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-page" data-href="https://www.facebook.com/wusmsnhc?fref=ts" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/wusmsnhc?fref=ts"><a href="https://www.facebook.com/wusmsnhc?fref=ts">Washington University Saturday Neighborhood Health Clinic</a></blockquote></div></div>

**Comment by lizmaidl** [comment]
dammit...

**Comment by justinrporter** [comment]
done with #24
