### ISSUE TITLE
can we make a tab for news? 

### ISSUE THREAD

**Issue by lizmaidl** [SaturdayNeighborhoodHealthClinic/snhc-web#23]
@radhikajain @ecd25 
it might be nice to be able to post things like the Outlook article, publications, etc. that could come up about the clinic

**Comment by radhikajain** [comment]
great idea! i was envisioning this as some kind of "In the Press" box on the home page that you could scroll through to see links to articles about us

**Comment by justinrporter** [comment]
Something that I've seen before is a sidebar that shows a twitter feed. That way, we can tweet little news items + links, and not have to update the website. It would work really well with our current technical setup, if we can get it working with our needs!

**Comment by radhikajain** [comment]
like, we should create an snhc twitter?

**Comment by justinrporter** [comment]
Yeah! Then we just tweet interesting stuff and it appears on our site!

**Comment by radhikajain** [comment]
I like this! Could be a great way to put out patient education materials as well.

**Comment by lizmaidl** [comment]
Is there a way we could just do this with the Facebook? Seems a bit like duplication of effort 

Elizabeth Maidl
Washington University School of Medicine in St. Louis
MD Candidate | Class of 2018
maidle@wusm.wustl.edu
(507) 272-1615

On Apr 9, 2015, at 00:00, radhikajain notifications@github.com wrote:

I like this! Could be a great way to put out patient education materials as well.
�
Reply to this email directly or 
view it on GitHub.

 

The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended
 recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone
 or return mail.

**Comment by justinrporter** [comment]
Facebook is integrated with #24 .
