### ISSUE TITLE
Tab for Spanish Speakers

### ISSUE THREAD

**Issue by lizmaidl** [SaturdayNeighborhoodHealthClinic/snhc-web#32]
can we make a tab to include basic clinic information for spanish speakers?

**Comment by ecd25** [comment]
Seconded!

**Comment by justinrporter** [comment]
Yeah, this could be done quite easily. @lizmaidl if you look at the first commit in PR #31 , you can see how I added a new tab to the "services" menu bar item. You already know how to do the rest! (Except the Spanish, which I'm no better with than you!)
