### ISSUE TITLE
 rotating landing page banner

### ISSUE THREAD

**Issue by radhikajain** [SaturdayNeighborhoodHealthClinic/snhc-web#7]
Can we rotate between saturday clinic and specialty clinic? Also would be great for landing page to say "SNHC" and then separate banners to say "Saturday Neighborhood Health Clinic" and "Specialty Neighborhood Health Clinic"

**Comment by justinrporter** [comment]
@radhikajain  Sure. The question becomes then, what is our organization's name? The upper right hand corner also always says SNHC. I guess I figured that the Wednesday Clinic was a service of the Saturday Neighborhood Health Clinic...

But it's your brand, so you tell me what you want.

**Comment by radhikajain** [comment]
great question. The way Sagar and Miriam outlined their vision to us, in the long long long term they want SNHC to be "Satellite Neighborhood Health Clinic," featuring clinics all over St. Louis that operate on different days. And although that is a long-term goal, they want to move away from the "Saturday" focus, especially so that people don't get confused re: specialty nights on Wednesdays. Hence, they want to emphasize "SNHC" = Saturday Neighborhood Health Clinic AND Specialty Night Health Clinic. 

But of course we can redefine this however we see fit. Let's talk about it a bit more.

**Comment by justinrporter** [comment]
Interesting. Ok! Definitely bears further discussion. As we all know, brand confusion can be a death sentence!

Another issue we want to think about with having a carousel (as it's called in the business) is that is soaks up bandwidth for each image we use, which could become problematic for folks with slow 'net connections or mobile-only devices. Something to keep in mind when adding images all over the place.

**Comment by radhikajain** [comment]
absolutely, you bring up a good point. We should definitely be clear for ourselves.

yes, I know Alex brought that up in his resource website! Maybe not a priority...would definitely rather have people able to use the website regardless of wifi strength...

**Comment by justinrporter** [comment]
Won't fix.
