### ISSUE TITLE
Separate Saturday vs. Specialty clinic dates

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/snhc-web#8]
Under "upcoming clinic dates" on the services page, can you please make two columns of dates one under the header Saturday Clinic that displays the next four Saturdays and the other under the heading Specialty Clinic that lists the next four specialty clinic dates?

kthxbai

**Comment by justinrporter** [comment]
@ecd25 currently not a trivial modification. How high priority is this to you?

**Comment by justinrporter** [comment]
Not high priority. We can reopen this if it's deemed critical.
