### ISSUE TITLE
Photos in the titles

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/snhc-web#9]
We will get you more and better photos, but in the meantime, can you please put some nice photos in the banners at the top of each page?

**Comment by justinrporter** [comment]
So, I meant to talk about this @ecd25 @radhikajain , because I tried it and it looked bad. It was hard to read and just generally ugly. We'll need to talk about it at our next meeting, I think.

**Comment by radhikajain** [comment]
okay i'm okay with just the green for now! maybe we could try using a black and white photo

**Comment by justinrporter** [comment]
So, let's call this low priority, maybe even hold off until we have the photos we eventually want to use? @ecd25 @radhikajain

**Comment by justinrporter** [comment]
Closing this issue until we have more images or decide to do it.
